/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShariaCommitteeRouteImport } from './routes/sharia-committee'
import { Route as PricingEngineRouteImport } from './routes/pricing-engine'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as DigitalCurrencyRouteImport } from './routes/digital-currency'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedThreeWayRouteImport } from './routes/_authenticated/three-way'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedNewListingRouteImport } from './routes/_authenticated/new-listing'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOffersIdRouteImport } from './routes/_authenticated/offers.$id'
import { Route as AuthenticatedOfferListingIdRouteImport } from './routes/_authenticated/offer.$listingId'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin.disputes'

const ShariaCommitteeRoute = ShariaCommitteeRouteImport.update({
  id: '/sharia-committee',
  path: '/sharia-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingEngineRoute = PricingEngineRouteImport.update({
  id: '/pricing-engine',
  path: '/pricing-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalCurrencyRoute = DigitalCurrencyRouteImport.update({
  id: '/digital-currency',
  path: '/digital-currency',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThreeWayRoute = AuthenticatedThreeWayRouteImport.update({
  id: '/three-way',
  path: '/three-way',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewListingRoute = AuthenticatedNewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersIdRoute = AuthenticatedOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOffersRoute,
} as any)
const AuthenticatedOfferListingIdRoute =
  AuthenticatedOfferListingIdRouteImport.update({
    id: '/offer/$listingId',
    path: '/offer/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/digital-currency': typeof DigitalCurrencyRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/disputes': typeof AuthenticatedDisputesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/three-way': typeof AuthenticatedThreeWayRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/digital-currency': typeof DigitalCurrencyRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/disputes': typeof AuthenticatedDisputesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/three-way': typeof AuthenticatedThreeWayRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/digital-currency': typeof DigitalCurrencyRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/new-listing': typeof AuthenticatedNewListingRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/three-way': typeof AuthenticatedThreeWayRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/_authenticated/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/digital-currency'
    | '/premium'
    | '/pricing-engine'
    | '/sharia-committee'
    | '/admin'
    | '/disputes'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/profile'
    | '/three-way'
    | '/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/legal/$doc'
    | '/listings/$id'
    | '/admin/disputes'
    | '/admin/monitoring'
    | '/offer/$listingId'
    | '/offers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/digital-currency'
    | '/premium'
    | '/pricing-engine'
    | '/sharia-committee'
    | '/admin'
    | '/disputes'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/profile'
    | '/three-way'
    | '/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/legal/$doc'
    | '/listings/$id'
    | '/admin/disputes'
    | '/admin/monitoring'
    | '/offer/$listingId'
    | '/offers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/digital-currency'
    | '/premium'
    | '/pricing-engine'
    | '/sharia-committee'
    | '/_authenticated/admin'
    | '/_authenticated/disputes'
    | '/_authenticated/my-listings'
    | '/_authenticated/new-listing'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/three-way'
    | '/_authenticated/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/legal/$doc'
    | '/listings/$id'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/offer/$listingId'
    | '/_authenticated/offers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DigitalCurrencyRoute: typeof DigitalCurrencyRoute
  PremiumRoute: typeof PremiumRoute
  PricingEngineRoute: typeof PricingEngineRoute
  ShariaCommitteeRoute: typeof ShariaCommitteeRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  LegalDocRoute: typeof LegalDocRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sharia-committee': {
      id: '/sharia-committee'
      path: '/sharia-committee'
      fullPath: '/sharia-committee'
      preLoaderRoute: typeof ShariaCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-engine': {
      id: '/pricing-engine'
      path: '/pricing-engine'
      fullPath: '/pricing-engine'
      preLoaderRoute: typeof PricingEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-currency': {
      id: '/digital-currency'
      path: '/digital-currency'
      fullPath: '/digital-currency'
      preLoaderRoute: typeof DigitalCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/three-way': {
      id: '/_authenticated/three-way'
      path: '/three-way'
      fullPath: '/three-way'
      preLoaderRoute: typeof AuthenticatedThreeWayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-listing': {
      id: '/_authenticated/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof AuthenticatedNewListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/$id': {
      id: '/_authenticated/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AuthenticatedOffersIdRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/offer/$listingId': {
      id: '/_authenticated/offer/$listingId'
      path: '/offer/$listingId'
      fullPath: '/offer/$listingId'
      preLoaderRoute: typeof AuthenticatedOfferListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOffersRouteChildren {
  AuthenticatedOffersIdRoute: typeof AuthenticatedOffersIdRoute
}

const AuthenticatedOffersRouteChildren: AuthenticatedOffersRouteChildren = {
  AuthenticatedOffersIdRoute: AuthenticatedOffersIdRoute,
}

const AuthenticatedOffersRouteWithChildren =
  AuthenticatedOffersRoute._addFileChildren(AuthenticatedOffersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNewListingRoute: typeof AuthenticatedNewListingRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedThreeWayRoute: typeof AuthenticatedThreeWayRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedOfferListingIdRoute: typeof AuthenticatedOfferListingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNewListingRoute: AuthenticatedNewListingRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedThreeWayRoute: AuthenticatedThreeWayRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedOfferListingIdRoute: AuthenticatedOfferListingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DigitalCurrencyRoute: DigitalCurrencyRoute,
  PremiumRoute: PremiumRoute,
  PricingEngineRoute: PricingEngineRoute,
  ShariaCommitteeRoute: ShariaCommitteeRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  LegalDocRoute: LegalDocRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
