/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShariaCommitteeRouteImport } from './routes/sharia-committee'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingEngineRouteImport } from './routes/pricing-engine'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DigitalCurrencyRouteImport } from './routes/digital-currency'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsCallbackRouteImport } from './routes/payments/callback'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedThreeWayRouteImport } from './routes/_authenticated/three-way'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedNewListingRouteImport } from './routes/_authenticated/new-listing'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedSupportIdRouteImport } from './routes/_authenticated/support.$id'
import { Route as AuthenticatedOffersIdRouteImport } from './routes/_authenticated/offers.$id'
import { Route as AuthenticatedOfferListingIdRouteImport } from './routes/_authenticated/offer.$listingId'
import { Route as AuthenticatedAdminWaitlistRouteImport } from './routes/_authenticated/admin.waitlist'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminShippingCitiesRouteImport } from './routes/_authenticated/admin.shipping-cities'
import { Route as AuthenticatedAdminPaymentsSandboxRouteImport } from './routes/_authenticated/admin.payments-sandbox'
import { Route as AuthenticatedAdminPaymentsFinanceRouteImport } from './routes/_authenticated/admin.payments-finance'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as AuthenticatedAdminFraudRouteImport } from './routes/_authenticated/admin.fraud'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin.disputes'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicWebhooksFawaterakRouteImport } from './routes/api/public/webhooks/fawaterak'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShariaCommitteeRoute = ShariaCommitteeRouteImport.update({
  id: '/sharia-committee',
  path: '/sharia-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingEngineRoute = PricingEngineRouteImport.update({
  id: '/pricing-engine',
  path: '/pricing-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalCurrencyRoute = DigitalCurrencyRouteImport.update({
  id: '/digital-currency',
  path: '/digital-currency',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsCallbackRoute = PaymentsCallbackRouteImport.update({
  id: '/payments/callback',
  path: '/payments/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThreeWayRoute = AuthenticatedThreeWayRouteImport.update({
  id: '/three-way',
  path: '/three-way',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewListingRoute = AuthenticatedNewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSupportIdRoute = AuthenticatedSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSupportRoute,
} as any)
const AuthenticatedOffersIdRoute = AuthenticatedOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOffersRoute,
} as any)
const AuthenticatedOfferListingIdRoute =
  AuthenticatedOfferListingIdRouteImport.update({
    id: '/offer/$listingId',
    path: '/offer/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWaitlistRoute =
  AuthenticatedAdminWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShippingCitiesRoute =
  AuthenticatedAdminShippingCitiesRouteImport.update({
    id: '/shipping-cities',
    path: '/shipping-cities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsSandboxRoute =
  AuthenticatedAdminPaymentsSandboxRouteImport.update({
    id: '/payments-sandbox',
    path: '/payments-sandbox',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsFinanceRoute =
  AuthenticatedAdminPaymentsFinanceRouteImport.update({
    id: '/payments-finance',
    path: '/payments-finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFraudRoute = AuthenticatedAdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksFawaterakRoute =
  ApiPublicWebhooksFawaterakRouteImport.update({
    id: '/api/public/webhooks/fawaterak',
    path: '/api/public/webhooks/fawaterak',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/digital-currency': typeof DigitalCurrencyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/disputes': typeof AuthenticatedDisputesRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/three-way': typeof AuthenticatedThreeWayRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/payments-finance': typeof AuthenticatedAdminPaymentsFinanceRoute
  '/admin/payments-sandbox': typeof AuthenticatedAdminPaymentsSandboxRoute
  '/admin/shipping-cities': typeof AuthenticatedAdminShippingCitiesRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/api/public/webhooks/fawaterak': typeof ApiPublicWebhooksFawaterakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/digital-currency': typeof DigitalCurrencyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/disputes': typeof AuthenticatedDisputesRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/three-way': typeof AuthenticatedThreeWayRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/payments-finance': typeof AuthenticatedAdminPaymentsFinanceRoute
  '/admin/payments-sandbox': typeof AuthenticatedAdminPaymentsSandboxRoute
  '/admin/shipping-cities': typeof AuthenticatedAdminShippingCitiesRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/api/public/webhooks/fawaterak': typeof ApiPublicWebhooksFawaterakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/digital-currency': typeof DigitalCurrencyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mcp': typeof McpRoute
  '/premium': typeof PremiumRoute
  '/pricing-engine': typeof PricingEngineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sharia-committee': typeof ShariaCommitteeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/new-listing': typeof AuthenticatedNewListingRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRouteWithChildren
  '/_authenticated/three-way': typeof AuthenticatedThreeWayRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/listings/$id': typeof ListingsIdRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/payments-finance': typeof AuthenticatedAdminPaymentsFinanceRoute
  '/_authenticated/admin/payments-sandbox': typeof AuthenticatedAdminPaymentsSandboxRoute
  '/_authenticated/admin/shipping-cities': typeof AuthenticatedAdminShippingCitiesRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/_authenticated/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/_authenticated/offers/$id': typeof AuthenticatedOffersIdRoute
  '/_authenticated/support/$id': typeof AuthenticatedSupportIdRoute
  '/api/public/webhooks/fawaterak': typeof ApiPublicWebhooksFawaterakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/digital-currency'
    | '/leaderboard'
    | '/mcp'
    | '/premium'
    | '/pricing-engine'
    | '/reset-password'
    | '/robots.txt'
    | '/sharia-committee'
    | '/sitemap.xml'
    | '/waitlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/disputes'
    | '/kyc'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/payments'
    | '/profile'
    | '/referrals'
    | '/support'
    | '/three-way'
    | '/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/legal/$doc'
    | '/listings/$id'
    | '/payments/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/emails'
    | '/admin/finance'
    | '/admin/fraud'
    | '/admin/monitoring'
    | '/admin/payments-finance'
    | '/admin/payments-sandbox'
    | '/admin/shipping-cities'
    | '/admin/support'
    | '/admin/waitlist'
    | '/offer/$listingId'
    | '/offers/$id'
    | '/support/$id'
    | '/api/public/webhooks/fawaterak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/digital-currency'
    | '/leaderboard'
    | '/mcp'
    | '/premium'
    | '/pricing-engine'
    | '/reset-password'
    | '/robots.txt'
    | '/sharia-committee'
    | '/sitemap.xml'
    | '/waitlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/disputes'
    | '/kyc'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/payments'
    | '/profile'
    | '/referrals'
    | '/support'
    | '/three-way'
    | '/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/legal/$doc'
    | '/listings/$id'
    | '/payments/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/emails'
    | '/admin/finance'
    | '/admin/fraud'
    | '/admin/monitoring'
    | '/admin/payments-finance'
    | '/admin/payments-sandbox'
    | '/admin/shipping-cities'
    | '/admin/support'
    | '/admin/waitlist'
    | '/offer/$listingId'
    | '/offers/$id'
    | '/support/$id'
    | '/api/public/webhooks/fawaterak'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/digital-currency'
    | '/leaderboard'
    | '/mcp'
    | '/premium'
    | '/pricing-engine'
    | '/reset-password'
    | '/robots.txt'
    | '/sharia-committee'
    | '/sitemap.xml'
    | '/waitlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/disputes'
    | '/_authenticated/kyc'
    | '/_authenticated/my-listings'
    | '/_authenticated/new-listing'
    | '/_authenticated/offers'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/support'
    | '/_authenticated/three-way'
    | '/_authenticated/transactions'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/blog/$slug'
    | '/legal/$doc'
    | '/listings/$id'
    | '/payments/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/fraud'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/payments-finance'
    | '/_authenticated/admin/payments-sandbox'
    | '/_authenticated/admin/shipping-cities'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/waitlist'
    | '/_authenticated/offer/$listingId'
    | '/_authenticated/offers/$id'
    | '/_authenticated/support/$id'
    | '/api/public/webhooks/fawaterak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DigitalCurrencyRoute: typeof DigitalCurrencyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  McpRoute: typeof McpRoute
  PremiumRoute: typeof PremiumRoute
  PricingEngineRoute: typeof PricingEngineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShariaCommitteeRoute: typeof ShariaCommitteeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WaitlistRoute: typeof WaitlistRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  LegalDocRoute: typeof LegalDocRoute
  ListingsIdRoute: typeof ListingsIdRoute
  PaymentsCallbackRoute: typeof PaymentsCallbackRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhooksFawaterakRoute: typeof ApiPublicWebhooksFawaterakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharia-committee': {
      id: '/sharia-committee'
      path: '/sharia-committee'
      fullPath: '/sharia-committee'
      preLoaderRoute: typeof ShariaCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-engine': {
      id: '/pricing-engine'
      path: '/pricing-engine'
      fullPath: '/pricing-engine'
      preLoaderRoute: typeof PricingEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-currency': {
      id: '/digital-currency'
      path: '/digital-currency'
      fullPath: '/digital-currency'
      preLoaderRoute: typeof DigitalCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/callback': {
      id: '/payments/callback'
      path: '/payments/callback'
      fullPath: '/payments/callback'
      preLoaderRoute: typeof PaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/three-way': {
      id: '/_authenticated/three-way'
      path: '/three-way'
      fullPath: '/three-way'
      preLoaderRoute: typeof AuthenticatedThreeWayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-listing': {
      id: '/_authenticated/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof AuthenticatedNewListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support/$id': {
      id: '/_authenticated/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AuthenticatedSupportIdRouteImport
      parentRoute: typeof AuthenticatedSupportRoute
    }
    '/_authenticated/offers/$id': {
      id: '/_authenticated/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AuthenticatedOffersIdRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/offer/$listingId': {
      id: '/_authenticated/offer/$listingId'
      path: '/offer/$listingId'
      fullPath: '/offer/$listingId'
      preLoaderRoute: typeof AuthenticatedOfferListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/waitlist': {
      id: '/_authenticated/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AuthenticatedAdminWaitlistRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shipping-cities': {
      id: '/_authenticated/admin/shipping-cities'
      path: '/shipping-cities'
      fullPath: '/admin/shipping-cities'
      preLoaderRoute: typeof AuthenticatedAdminShippingCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments-sandbox': {
      id: '/_authenticated/admin/payments-sandbox'
      path: '/payments-sandbox'
      fullPath: '/admin/payments-sandbox'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsSandboxRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments-finance': {
      id: '/_authenticated/admin/payments-finance'
      path: '/payments-finance'
      fullPath: '/admin/payments-finance'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fraud': {
      id: '/_authenticated/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AuthenticatedAdminFraudRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/fawaterak': {
      id: '/api/public/webhooks/fawaterak'
      path: '/api/public/webhooks/fawaterak'
      fullPath: '/api/public/webhooks/fawaterak'
      preLoaderRoute: typeof ApiPublicWebhooksFawaterakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFraudRoute: typeof AuthenticatedAdminFraudRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminPaymentsFinanceRoute: typeof AuthenticatedAdminPaymentsFinanceRoute
  AuthenticatedAdminPaymentsSandboxRoute: typeof AuthenticatedAdminPaymentsSandboxRoute
  AuthenticatedAdminShippingCitiesRoute: typeof AuthenticatedAdminShippingCitiesRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminWaitlistRoute: typeof AuthenticatedAdminWaitlistRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminFraudRoute: AuthenticatedAdminFraudRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminPaymentsFinanceRoute:
    AuthenticatedAdminPaymentsFinanceRoute,
  AuthenticatedAdminPaymentsSandboxRoute:
    AuthenticatedAdminPaymentsSandboxRoute,
  AuthenticatedAdminShippingCitiesRoute: AuthenticatedAdminShippingCitiesRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminWaitlistRoute: AuthenticatedAdminWaitlistRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOffersRouteChildren {
  AuthenticatedOffersIdRoute: typeof AuthenticatedOffersIdRoute
}

const AuthenticatedOffersRouteChildren: AuthenticatedOffersRouteChildren = {
  AuthenticatedOffersIdRoute: AuthenticatedOffersIdRoute,
}

const AuthenticatedOffersRouteWithChildren =
  AuthenticatedOffersRoute._addFileChildren(AuthenticatedOffersRouteChildren)

interface AuthenticatedSupportRouteChildren {
  AuthenticatedSupportIdRoute: typeof AuthenticatedSupportIdRoute
}

const AuthenticatedSupportRouteChildren: AuthenticatedSupportRouteChildren = {
  AuthenticatedSupportIdRoute: AuthenticatedSupportIdRoute,
}

const AuthenticatedSupportRouteWithChildren =
  AuthenticatedSupportRoute._addFileChildren(AuthenticatedSupportRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNewListingRoute: typeof AuthenticatedNewListingRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRouteWithChildren
  AuthenticatedThreeWayRoute: typeof AuthenticatedThreeWayRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedOfferListingIdRoute: typeof AuthenticatedOfferListingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNewListingRoute: AuthenticatedNewListingRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRouteWithChildren,
  AuthenticatedThreeWayRoute: AuthenticatedThreeWayRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedOfferListingIdRoute: AuthenticatedOfferListingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DigitalCurrencyRoute: DigitalCurrencyRoute,
  LeaderboardRoute: LeaderboardRoute,
  McpRoute: McpRoute,
  PremiumRoute: PremiumRoute,
  PricingEngineRoute: PricingEngineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShariaCommitteeRoute: ShariaCommitteeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WaitlistRoute: WaitlistRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  LegalDocRoute: LegalDocRoute,
  ListingsIdRoute: ListingsIdRoute,
  PaymentsCallbackRoute: PaymentsCallbackRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhooksFawaterakRoute: ApiPublicWebhooksFawaterakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
