/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedNewListingRouteImport } from './routes/_authenticated/new-listing'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedOffersIdRouteImport } from './routes/_authenticated/offers.$id'
import { Route as AuthenticatedOfferListingIdRouteImport } from './routes/_authenticated/offer.$listingId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewListingRoute = AuthenticatedNewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersIdRoute = AuthenticatedOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOffersRoute,
} as any)
const AuthenticatedOfferListingIdRoute =
  AuthenticatedOfferListingIdRouteImport.update({
    id: '/offer/$listingId',
    path: '/offer/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/listings/$id': typeof ListingsIdRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/new-listing': typeof AuthenticatedNewListingRoute
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/listings/$id': typeof ListingsIdRoute
  '/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/new-listing': typeof AuthenticatedNewListingRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/listings/$id': typeof ListingsIdRoute
  '/_authenticated/offer/$listingId': typeof AuthenticatedOfferListingIdRoute
  '/_authenticated/offers/$id': typeof AuthenticatedOffersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/profile'
    | '/listings/$id'
    | '/offer/$listingId'
    | '/offers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-listings'
    | '/new-listing'
    | '/offers'
    | '/profile'
    | '/listings/$id'
    | '/offer/$listingId'
    | '/offers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/my-listings'
    | '/_authenticated/new-listing'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/listings/$id'
    | '/_authenticated/offer/$listingId'
    | '/_authenticated/offers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-listing': {
      id: '/_authenticated/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof AuthenticatedNewListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/$id': {
      id: '/_authenticated/offers/$id'
      path: '/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof AuthenticatedOffersIdRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/offer/$listingId': {
      id: '/_authenticated/offer/$listingId'
      path: '/offer/$listingId'
      fullPath: '/offer/$listingId'
      preLoaderRoute: typeof AuthenticatedOfferListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedOffersRouteChildren {
  AuthenticatedOffersIdRoute: typeof AuthenticatedOffersIdRoute
}

const AuthenticatedOffersRouteChildren: AuthenticatedOffersRouteChildren = {
  AuthenticatedOffersIdRoute: AuthenticatedOffersIdRoute,
}

const AuthenticatedOffersRouteWithChildren =
  AuthenticatedOffersRoute._addFileChildren(AuthenticatedOffersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNewListingRoute: typeof AuthenticatedNewListingRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOfferListingIdRoute: typeof AuthenticatedOfferListingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNewListingRoute: AuthenticatedNewListingRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOfferListingIdRoute: AuthenticatedOfferListingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
